### ISSUE TITLE
NodeJS & Javascript question (You have 4 days to complete the task)

### ISSUE THREAD

**Issue by Hawaiideveloper** [alexigazu/interview-questions#2]
#### You have 4 days to complete starting on Monday (January 4, 2020 4am) ending Thursday (January 7, 2020 11:59pm)
---
# Question 2 has four parts:

### Part 1: 
What does this code do [here](https://github.com/kaloraat/nodeapi/blob/aa8b077918a2a1f16fe3541e2d46c1f0ce027cd4/models/post.js#L13)

Tell me what it does

### Part 2: 
Take the repository from [the backend nodeAPI](https://github.com/kaloraat/nodeapi) then compile it,... make sure to 
```Read the directions```

&

Take the repository from the [front-end-api](https://github.com/kaloraat/react-front) then compile it,  make sure to 
```Read the directions```

###### You can use issues within the repos above, to ask the author questions if you like

Show a screenshot of the compiled application and its front end within the web browser of your choice. 

### Part 3: 
Show the application working with screenshots:
- [ ] Create a user named "A_happy_user"
- [ ] Delete that user
- [ ] Create a post named "hammer_mc" and add a photo
- [ ] Delete a post

### Part 4: 
Look at the part 1 again,  now add the required code to the application so that the user can have 4 additional photos for each post and profile.  Then present additional screenshots showing it works.
